channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake=7.16.0
  - python=3.9
  - pandas=1.3.2
  - pysam=0.22.1
  - perl
  - julia
#  - matplotlib
#  - graphviz
  - bcftools=1.15
  - samtools=1.15
  - bwa=0.7.17
  - r-base
  - r-optparse
  - r-tidyverse
#  - pysam =0.19
#  - pygments
